config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/instagram/callback', to: 'sessions#create'
  get 'signout', to: "sessions#destroy"
  resources :user, only: [:show] do
    resources :albums, only: [:new, :create, :index, :show] do
      resources :photos, only: [:index, :show]
    end
    resources :photos, only: [:new, :create]
  end

  get '/user-album', to: "users#album"

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album
  has_one :user, through: :album

  accepts_nested_attributes_for :album
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums
  has_many :photos, through: :albums
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.token = auth["credentials"]["token"]
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @user = current_user
    @albums = @user.albums
  end

  def show
    @user = current_user
    @album = @user.albums.find(params[:id])
    @photos = @album.photos
  end



  private
    def album_params
      parmas.require(:album).permit(:name, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @user = current_user
    @photos = @user.albums.find(params[:album_id]).photos
  end


  def create
    @user = current_user
    @photo = @user.photos.new(filter_params(photo_params))
    respond_to do |format|
      if @photo.save
        format.json { render json: @photo.to_json }
      else
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def photo_params
    params.require(:photo).permit(:album_id, :url, :name, :album_attributes => [:title, :user_id])
  end

  def filter_params(photo_params)
    new_params = photo_params.dup
    if new_params[:album_id].present?
      new_params.delete(:album_attributes)
    end
    new_params
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    @user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = @user.id
    f = params[:code]
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to '/'
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:user_id])
  end

  def album
    redirect_to user_album_path(current_user, params[:album][:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user.present?
      @user = current_user
      @photo = @user.photos.new
      @album = @photo.build_album
      @albums = @user.albums
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<%@albums.each do |album| %>
  <a href='/user/<%=current_user.id%>/albums/<%=album.id%>/photos'>
    <img src = '<%=album.photos.first.url%>' class = "thumbnails" id = "album-cover">
    <br>
    <div class = 'album'>
      <%= album.title %>
    </div>
  </a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramOauthPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</div>
</body>
</html>

app/views/photos/index.html.erb
<%@photos.each do |photo|%>
  <img src = '<%=photo.url%>' class = "thumbnails">
  <%= photo.name %>
<% end %>

app/views/welcome/_album.html.erb
<%if current_user%>
  <div class="row">
  <%@albums.each do |album| %>
  <%if album.photos.first != nil%>
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <a href='/user/<%=current_user.id%>/albums/<%=album.id%>/photos' class="thumbnail"]>
            <img src='<%=album.photos.first.url%>' alt="...">
        </a>
        <div class="caption">
          <h5>Album: <%=album.title%></h5>

        </div>
      </div>
    </div>
  <% end %>
  <%end%>
  </div>
<%end%>

app/views/welcome/_form.html.erb
  <%= form_for [@user, @photo], url: user_photos_path(current_user), html: { class: "popupform", 'data-id'=> "#{@user.id}"} do |f|%>
    <% if current_user.albums.any? %>
      <%=f.label :album_id, "Select an album"%>
      <%=f.collection_select(:album_id, @user.albums.all << @user.albums.new(:title => "New Album"), :id, :title)%>
      <div class = "create-album" hidden=true>
        <%=f.fields_for :album, @album do |fa| %>
          <%=fa.label :title, "Create Album with Title" %>
          <%=fa.text_field :title %>
        <% end %>
      </div>
    <% else %>
      <%= f.fields_for :album, @album do |fa| %>
        <%=fa.label :title, "Create Album with Title" %>
        <%=fa.text_field :title%>
      <% end %>
    <% end %>
    <%= f.label :name, "Photo name" %>
    <%= f.text_field :name%>
    <%=button_tag "Add Item", class: "save-photo-btn" %>
  <% end %>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Instagralbums</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%if current_user%>
          <p class="navbar-text"> <%="Welcome to your albums, #{current_user.name}"%> </p>
          <li> <%=link_to 'Sign Out', signout_path%> </li>
        <%else%>
          <li><a href="/auth/instagram">Sign in with Instagram</a></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>
<%= javascript_include_tag "application" %>
<div class = "container">
  <%if current_user%>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      See my albums
    </button>
    <div class = "findandsave">
      <div class = "token" data-token = "<%=current_user.token%>" ></div>
      <br>
      <%=button_tag "Search by current location", class: "current-location-btn" %>
      <div class ="location-options"></div>
      <p> or </p>
      <%=form_tag "#", :onSubmit => "return false" do %>
        <%= text_field_tag :tag, "enter tag here" %>
        <%= submit_tag "Search", class: "photo-search" %>
      <% end %>
      <%= render "form" %>
    </div>

  <% end %>
  <div class="photos-slideshow">
  </div>
</div>
<footer class ="footer">
  <div class ="container"></div>
</footer>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Albums</h4>
      </div>
      <div class="modal-body">
        <%= render "album"%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" >Ok</button>
      </div>
    </div>
  </div>
</div>